### ISSUE TITLE
Image moving for some reason?

### ISSUE THREAD

**Issue by erinmilling** [erinmilling/dsn1674-project-3#1]
Im having an issue with expanding my website, the coconut image moves up over the .link
![screen shot 2015-04-21 at 8 58 40 pm](https://cloud.githubusercontent.com/assets/10464609/7265531/5cd87824-e869-11e4-9633-85d1239e67f7.png)
![screen shot 2015-04-21 at 8 58 22 pm](https://cloud.githubusercontent.com/assets/10464609/7265532/5fa94880-e869-11e4-8542-cc011e4848a2.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
Delete the position relative and top.

**Comment by erinmilling** [comment]
I did that but then when I shrink my browser down to 320px the image slides down

**Comment by erinmilling** [comment]
I did that but then when I shrink my browser down to 320px the image slides down

**Comment by erinmilling** [comment]
I did that but then when I shrink my browser down to 320px the image slides down

**Comment by erinmilling** [comment]
I did that but then when I shrink my browser down to 320px the image slides down
