### ISSUE TITLE
White space after footer!!

### ISSUE THREAD

**Issue by erinmilling** [erinmilling/dsn1674-project-3#7]
![screen shot 2015-04-24 at 10 49 29 am](https://cloud.githubusercontent.com/assets/10464609/7321359/bede2a66-ea6f-11e4-9576-92748214be25.png)
![screen shot 2015-04-24 at 10 49 19 am](https://cloud.githubusercontent.com/assets/10464609/7321369/cc27c038-ea6f-11e4-9edf-129660649056.png)
![screen shot 2015-04-24 at 10 49 07 am](https://cloud.githubusercontent.com/assets/10464609/7321381/d6bcf978-ea6f-11e4-8503-c2e0f2acdf7d.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
Delete the position relative and top from the footer.
